# Generated by Django 5.1.2 on 2024-11-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('usedFor', models.TextField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('category', models.CharField(choices=[('herbs', 'Herbs'), ('shrubs', 'Shrubs'), ('trees', 'Trees'), ('creepers', 'Creepers'), ('climbers', 'Climbers')], max_length=64)),
                ('isEdible', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
